version: '3.1'
services:
  consul:
    image: hashicorp/consul:latest
    restart: always
    container_name: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    extra_hosts:
      - "host.docker.internal:host-gateway"
