server:
  port: ${random.int(8080,8090)}
spring:
  application:
    name: Users
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: 172.30.208.1
        instance-id: ${spring.application.name}-${random.int(1,40)}
        health-check-interval: 3s
